import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body>
        <Header/>
        {children}
        <div style={{position:'absolute', bottom:0, backgroundColor:'black',color:'white', width:'100%', textAlign:'center', paddingTop:5, paddingBottom:5}}>🧑🏻‍💻 Developed by SarbZone</div>
        </body>
    </html>
  );
}
